# Generated by Django 3.0.6 on 2020-06-07 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
                ('department_image', models.FileField(upload_to='cake_departments/')),
            ],
        ),
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cake_name', models.CharField(max_length=255)),
                ('cake_image', models.FileField(upload_to='cake_images/')),
                ('half_kg_available', models.BooleanField(default=True)),
                ('maximum_kgs', models.IntegerField(default=10)),
                ('half_kg_price', models.IntegerField(default=0)),
                ('one_kg_price', models.IntegerField(default=0)),
                ('egg_less_price', models.IntegerField(default=50)),
                ('is_egless_available', models.BooleanField(default=True)),
                ('is_totally_eggless_cake', models.BooleanField(default=False)),
                ('custom_photo_upload', models.BooleanField(default=False)),
                ('does_this_have_flavours', models.BooleanField(default=False)),
                ('cake_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CakeDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='CakeShopDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.TextField(default='No Address!')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('falvour_name', models.CharField(max_length=255)),
                ('half_kg_available', models.BooleanField(default=True)),
                ('maximum_kgs', models.IntegerField(default=10)),
                ('half_kg_price', models.IntegerField(default=0)),
                ('one_kg_price', models.IntegerField(default=0)),
                ('egg_less_price', models.IntegerField(default=50)),
                ('is_egless_available', models.BooleanField(default=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cakes')),
            ],
        ),
        migrations.CreateModel(
            name='FlavourRoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('falvour_root', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_of_order', models.DateTimeField(auto_now=True)),
                ('occasion', models.CharField(max_length=100)),
                ('date_of_delivery', models.DateTimeField()),
                ('message_on_cake', models.CharField(max_length=255)),
                ('special_instructions', models.CharField(max_length=255)),
                ('eggless', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('cake_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cakes')),
                ('flavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Flavors')),
            ],
        ),
        migrations.CreateModel(
            name='UserOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('occasion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCakeShopRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CakeShopDetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCakeLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='cake_order_photos/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.OrderCake')),
            ],
        ),
        migrations.AddField(
            model_name='flavors',
            name='falvour_root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FlavourRoot'),
        ),
        migrations.AddField(
            model_name='cakedepartment',
            name='cake_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CakeShopDetails'),
        ),
    ]
