# Generated by Django 3.0.6 on 2020-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200610_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercake',
            name='special_instructions',
            field=models.CharField(default='No Special Instructions', max_length=255, null=True),
        ),
    ]
