# Generated by Django 3.0.6 on 2020-06-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200614_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercake',
            name='shape',
            field=models.CharField(default='Circle', max_length=100),
        ),
    ]
